apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: se3mlw6wu-go 
  janus-idp.io/tekton: se3mlw6wu-go
  backstage.io/kubernetes-id: se3mlw6wu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: se3mlw6wu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  