apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: se3mlw6wu-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:5f14aac90a3557843584bcb2c792cbb3c86c6276@sha256:66f73a73249fa2bc0f7b90da19b5fe9bc84779ee66ee6a77aa1287f24a2b2cb5
          name: container-image
