apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: se3mlw6wu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: se3mlw6wu-go 
  name: se3mlw6wu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: se3mlw6wu-go 
